spring.application.name=grant-java

# Absolute path (recommended)
spring.datasource.url=jdbc:h2:file:C:\\Users\\5607181\\Downloads\\h2_db\\grants-db-1


## OR relative to project root
#localhost:8080/h2-console
#spring.datasource.url=jdbc:h2:file:./data/grants-db
spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
server.servlet.context-path=/pixel-commanders/grant-application
#spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
logging.level.root=INFO
logging.level.org.tfg.grant_java = TRACE
lucene.index.path=C:\\Users\\5607181\\Downloads\\practice\\grant-application-java\\lucene-index
#use the below path for lucene indices if you deploy this application in linux
#lucene.index.path=/opt/grants/lucene-index
#lucene.analyzer=StandardAnalyzer
lucene.analyzer=LanguageAnalyzer

